name: secure_utils
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  basic_utils: ^5.8.2
  pointycastle: any

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
